In [1]:
import tensorflow as tf

In [10]:
import tensorflow as tf

tensor = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ],
    [
        [13, 14, 15],
        [16, 17, 18]
    ]
],dtype=tf.float16)

tensor


<tf.Tensor: shape=(3, 2, 3), dtype=float16, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]],

       [[13., 14., 15.],
        [16., 17., 18.]]], dtype=float16)>

In [5]:
tensor

<tf.Tensor: shape=(1, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])>

In [23]:
 change=tf.Variable([1,7])
no=tf.constant([5,5])

In [24]:
change[0].assign(3)
no[0]

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [30]:
tensor1=tf.Variable([1,2],[3,4],[5,6])

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [28]:
tf.random.shuffle(tensor1,seed=13)

In [29]:
import tensorflow as tf

# Creating a 2D tensor (matrix)
tensor1 = tf.Variable([[1, 2], [3, 4], [5, 6]])

# Shuffling the rows of the tensor
v = tf.random.shuffle(tensor1, seed=13)

print(v)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [31]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [34]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>